apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-probes-and-resources
  annotations:
    policies.kyverno.io/title: Require probes and resources
    policies.kyverno.io/category: Reliability
    policies.kyverno.io/subject: Pod
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-container-health-and-resource-controls
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Containers must define readiness and liveness probes (with periodSeconds) and CPU and memory requests."
        pattern:
          spec:
            containers:
              - readinessProbe:
                  periodSeconds: ">0"
                livenessProbe:
                  periodSeconds: ">0"
                resources:
                  requests:
                    memory: "?*"
                    cpu: "?*"
