apiVersion: v1
kind: Service
metadata:
  name: platform-service
  namespace: platform-example
  labels:
    app: platform-service
spec:
  type: ClusterIP
  selector:
    app: platform-service
  ports:
    - name: http
      port: 80
      targetPort: 8080

